Update terminal to wezterm, update color to catppuccin

diff --git a/.local/bin/scripts/rotate b/.local/bin/scripts/rotate
--- a/.local/bin/scripts/rotate
+++ b/.local/bin/scripts/rotate
@@ -22,45 +22,44 @@ TOUCHPAD='DLL096D:01 06CB:CDE6 Touchpad'
 TOUCHSCREEN='Wacom HID 4943 Finger touch'
 
 if [ -z "$1" ]; then
-  echo "Missing orientation."
-  echo "Usage: $0 [normal|inverted|left|right] [revert_seconds]"
-  echo
-  exit 1
+    echo "Missing orientation."
+    echo "Usage: $0 [normal|inverted|left|right] [revert_seconds]"
+    echo
+    exit 1
 fi
 
-function do_rotate
-{
-  xrandr --output $1 --rotate $2
+function do_rotate {
+    xrandr --output "$1" --rotate "$2"
 
-  TRANSFORM='Coordinate Transformation Matrix'
+    TRANSFORM='Coordinate Transformation Matrix'
 
-  case "$2" in
-    normal)
-      [ ! -z "$TOUCHPAD" ]    && xinput set-prop "$TOUCHPAD"    "$TRANSFORM" 1 0 0 0 1 0 0 0 1
-      [ ! -z "$TOUCHSCREEN" ] && xinput set-prop "$TOUCHSCREEN" "$TRANSFORM" 1 0 0 0 1 0 0 0 1
-      ;;
-    inverted)
-      [ ! -z "$TOUCHPAD" ]    && xinput set-prop "$TOUCHPAD"    "$TRANSFORM" -1 0 1 0 -1 1 0 0 1
-      [ ! -z "$TOUCHSCREEN" ] && xinput set-prop "$TOUCHSCREEN" "$TRANSFORM" -1 0 1 0 -1 1 0 0 1
-      ;;
-    left)
-      [ ! -z "$TOUCHPAD" ]    && xinput set-prop "$TOUCHPAD"    "$TRANSFORM" 0 -1 1 1 0 0 0 0 1
-      [ ! -z "$TOUCHSCREEN" ] && xinput set-prop "$TOUCHSCREEN" "$TRANSFORM" 0 -1 1 1 0 0 0 0 1
-      ;;
-    right)
-      [ ! -z "$TOUCHPAD" ]    && xinput set-prop "$TOUCHPAD"    "$TRANSFORM" 0 1 0 -1 0 1 0 0 1
-      [ ! -z "$TOUCHSCREEN" ] && xinput set-prop "$TOUCHSCREEN" "$TRANSFORM" 0 1 0 -1 0 1 0 0 1
-      ;;
-  esac
+    case "$2" in
+        normal)
+            [ -n "$TOUCHPAD" ]    && xinput set-prop "$TOUCHPAD"    "$TRANSFORM" 1 0 0 0 1 0 0 0 1
+            [ -n "$TOUCHSCREEN" ] && xinput set-prop "$TOUCHSCREEN" "$TRANSFORM" 1 0 0 0 1 0 0 0 1
+            ;;
+        inverted)
+            [ -n "$TOUCHPAD" ]    && xinput set-prop "$TOUCHPAD"    "$TRANSFORM" -1 0 1 0 -1 1 0 0 1
+            [ -n "$TOUCHSCREEN" ] && xinput set-prop "$TOUCHSCREEN" "$TRANSFORM" -1 0 1 0 -1 1 0 0 1
+            ;;
+        left)
+            [ -n "$TOUCHPAD" ]    && xinput set-prop "$TOUCHPAD"    "$TRANSFORM" 0 -1 1 1 0 0 0 0 1
+            [ -n "$TOUCHSCREEN" ] && xinput set-prop "$TOUCHSCREEN" "$TRANSFORM" 0 -1 1 1 0 0 0 0 1
+            ;;
+        right)
+            [ -n "$TOUCHPAD" ]    && xinput set-prop "$TOUCHPAD"    "$TRANSFORM" 0 1 0 -1 0 1 0 0 1
+            [ -n "$TOUCHSCREEN" ] && xinput set-prop "$TOUCHSCREEN" "$TRANSFORM" 0 1 0 -1 0 1 0 0 1
+            ;;
+    esac
 }
 
-XDISPLAY=`xrandr --current | grep primary | sed -e 's/ .*//g'`
-XROT=`xrandr --current --verbose | grep primary | egrep -o ' (normal|left|inverted|right) '`
+XDISPLAY=$(xrandr --current | grep primary | sed -e 's/ .*//g')
+XROT=$(xrandr --current --verbose | grep primary | grep -E -o ' (normal|left|inverted|right) ')
 
-do_rotate $XDISPLAY $1
+do_rotate "$XDISPLAY" "$1"
 
-if [ ! -z "$2" ]; then
-  sleep $2
-  do_rotate $XDISPLAY $XROT
-  exit 0
+if [ -n "$2" ]; then
+    sleep "$2"
+    do_rotate "$XDISPLAY" "$XROT"
+    exit 0
 fi
